[package]
name = "prpara"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.6.0"
nix = "0.26.1"
proc-maps = "0.3.0"
seahorse = "2.1.0"
thiserror = "1.0.38"
